### ISSUE TITLE
The AppVeyor/NuGet workflow for Serilog projects

### ISSUE THREAD

**Issue by MV10** [MV10/serilog-settings-delegates#3]
After bugging folks in the Serilog gitter discussion, I'm hoping someone familiar with Serilog releases will drop by this thread and school me on The Serilog Way. I'd like to publish this project to NuGet using AppVeyor. I've been using _Serilog.Settings.Configuration_ as a model. I think my main `csproj` and the `appveyor.yml` files are set up right (and `build.ps1` is just a direct copy, sans the "performance" build since I don't have that here).

After reviewing the AppVeyor docs, comparing to the YML, and poking around in what I can see in the public areas of the _Configuration_ repo, what still isn't clicking for me is the general workflow. For example, how release builds are kicked off and published; the nuances of publishing a package with a 1.0.0 version versus 1.0.0-dev-0001 (I see dev is handled by `build.ps1` via the branch name... but I also see it trying to publish when I check-in something like my current work in the "initial_appveyor_support" branch, too).

Do I need to consider creating something like [this](https://github.com/serilog-build) "Serilog Build Agent" account? (And if so, why, what role does it play?)

I'm also wondering about the handful of settings that aren't controlled by the YML file:

https://www.appveyor.com/docs/build-configuration/#appveyoryml-and-ui-coexistence

Links to relevant bits of this repo:

- [`initial_appveyor_support`](https://github.com/MV10/serilog-settings-delegates/tree/initial_appveyor_support) (branch)
- [`appveyor.yml`](https://github.com/MV10/serilog-settings-delegates/blob/initial_appveyor_support/appveyor.yml)
- [`build.ps1`](https://github.com/MV10/serilog-settings-delegates/blob/initial_appveyor_support/build.ps1)
- [`csproj`](https://github.com/MV10/serilog-settings-delegates/blob/initial_appveyor_support/src/Serilog.Settings.Delegates/Serilog.Settings.Delegates.csproj)

School me like I'm five. 👍 

(For anyone wondering about the origin of this project, see https://github.com/serilog/serilog-settings-configuration/issues/106)

**Comment by tsimbalar** [comment]
*(I had posted a longer answer, but Windows decided it was a good moment to restart 😠  )*

I am by no means an expert but the general idea is : 
- every push to any branch of the repo triggers a build
- every build generates a Nuget package (this is the `dotnet pack` part of `Build.ps1`
- the nuget package is not always published to nuget.org (this is the `on:branch: /^(master|dev)$/` in the `.yml` file) . You can still download it manually from the [build/artifacts page](https://ci.appveyor.com/project/serilog/serilog-settings-configuration/build/110/artifacts) in AppVeyor
- only builds on `master` create a release in GitHub

The version (*Major.minor.patch*) of the published package is defined in the `csproj` file (`<VersionPrefix>`). 
- on `master` the version number is left *as is* (this is a *Release package* in nuget)
- on other branches, a suffix starting with a `-` is appended (this makes it a [*pre-release* package](https://docs.microsoft.com/en-us/nuget/reference/package-versioning#pre-release-versions)). The suffix looks like `-{NameOfTheBranchTruncatedTo10Chars}-{TheIncrementalBuildNumberProvidedByAppVeyorPaddedWithZeros}`

I am not so sure about the need for a specific account and all the part about permissions is a bit blurry to me. @nblumhardt @merbla @adamchester can probably help on the subject. And the result of this discussion would probably a good paragraph for the *Serilog wiki* :)

**Comment by merbla** [comment]
@MV10 not sure this has everything, however HTH.

https://github.com/serilog/serilog/wiki/Repository-Structure

You will need to provision a NuGet key for yourself via the new [API Keys](https://www.nuget.org/account/apikeys) so that you can push your package.

**Comment by MV10** [comment]
Awesome.

![image](https://user-images.githubusercontent.com/794270/44547843-51d0da00-a6ea-11e8-87e3-6a06531c1fbd.png)

**Comment by MV10** [comment]
Oops, close-button misfire.

I guess my next question is how to do something like update the master-branch README without kicking off another build/release...

**Comment by MV10** [comment]
Notes to my future-self:

https://www.appveyor.com/docs/how-to/filtering-commits/

Add this:
```yml

only_commits:
  files:
    - Serilog.Settings.Delegates.sln
    - src/Serilog.Settings.Delegates/
```
